replicaCount: 1

image:
  repository: finance-processor-ui
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: fin-processor-ui.fin-processor.svc.cluster.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources: {}

livenessProbe:
  httpGet:
    path: /api/health
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
