name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - README.md
  pull_request_target:
    branches:
      - main
    types:
      - closed
    paths-ignore:
      - README.md

jobs:
  run-sanity-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Run ESlint
        run: npm run lint

      - name: Run tests
        run: npm test

  publish-test-coverage-report:
    runs-on: ubuntu-latest
    needs: [run-sanity-check]
    steps:
      - name: Publish test coverage report
        uses: actions/upload-artifact@v4
        with:
          name: Test coverage report
          path: coverage

  package:
    runs-on: ubuntu-latest
    needs: [run-sanity-check]
    steps:
      - name: Build project
        run: npm run build
